### ISSUE TITLE
Create a single compose file

### ISSUE THREAD

**Issue by LongLiveCHIEF** [busbud/devops-challenge-apps#1]
There isn't any reason to have multiple `compose` files. The whole point of the compose file is to describe multiple services, and doing so in a single file gives you the added benefit of using docker networking, orchestration, and security in your apps entire ecosystem.

I believe this is the biggest reason your #devopschallenge has received the feedback it has.  It's not a matter of time, it's become a matter of now having to refactor code just to start the challenge.

If you're going to challenge an engineer to set up an infrastructure, application design is just as important as the build, delivery, and hosting models.

**Comment by cdnbacon** [comment]
Thank you for the feedback :)
