### ISSUE TITLE
Rethink Part 4

### ISSUE THREAD

**Issue by LongLiveCHIEF** [busbud/devops-challenge-apps#4]
### Problem

As it's currently designed, part 4 (monitoring), would be a more appropriate interview question.  (similar reasons as #2 ).

I'd also like to add that as an engineer, I wouldn't want to answer these sorts of interview questions in a github repo, where other applicants following me would be able to see, learn, and improve upon my answers.

A selection is meant to be competitive, and I'd like to think that my own experiences have given me a competitive advantage. For any item you're asking the engineer to deliver in the current PR, ask yourself "is he giving away his competitive advantage"?  If so, this should be an interview question, not part of a code-challenge.
### Alternative

However, monitoring itself, is a great topic to put into a coding challenge. You might reword this part of the challenge to ask the engineer to create another application tier that handles monitoring of the other tiers.

**Comment by cdnbacon** [comment]
Thank you for the feedback, much appreciated :)
